import { useCallback, useEffect, useState } from 'react';
import { FileCheck2 } from 'lucide-react';
import PageHeader from '../../components/common/PageHeader';
import SearchInput from '../../components/common/SearchInput';
import DataTable from '../../components/common/DataTable';
import StatusBadge from '../../components/common/StatusBadge';
import ConfirmDialog from '../../components/common/ConfirmDialog';
import invoiceService from '../../services/invoice.service';
import { useDebounce } from '../../hooks/useDebounce';
import { formatCurrency, formatDate } from '../../utils/formatters';

/**
 * Real end to end via the built-in mock IRN provider until real NIC/GSP credentials are
 * configured (server/src/integrations/irn/) — see the "PENDING IMPLEMENTATION" comment on
 * nic.irn.provider.js. The generated IRN itself is not a genuine government registration.
 */
export default function GenerateIrnPage() {
  const [search, setSearch] = useState('');
  const debouncedSearch = useDebounce(search);
  const [state, setState] = useState({ loading: true, error: '', rows: [] });
  const [target, setTarget] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [result, setResult] = useState(null);
  const [genError, setGenError] = useState('');

  const load = useCallback(async () => {
    setState((s) => ({ ...s, loading: true, error: '' }));
    try {
      const res = await invoiceService.list({ search: debouncedSearch, irnStatus: 'NOT_GENERATED', status: 'GENERATED', limit: 50 });
      setState({ loading: false, error: '', rows: res.data || [] });
    } catch (err) {
      setState({ loading: false, error: err.message, rows: [] });
    }
  }, [debouncedSearch]);

  useEffect(() => { load(); }, [load]);

  const openConfirm = (invoice) => {
    setTarget(invoice);
    setResult(null);
    setGenError('');
  };

  const confirmGenerate = async () => {
    setGenerating(true);
    setGenError('');
    try {
      const res = await invoiceService.generateIrn(target._id);
      if (res.data?.success) {
        setResult(res.data);
        load();
      } else {
        setGenError(res.data?.error || res.message);
      }
    } catch (err) {
      setGenError(err.message);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div>
      <PageHeader title="Generate IRN" breadcrumb={[{ label: 'Invoices', to: '/invoices' }, { label: 'Generate IRN' }]} subtitle="Generate a GST e-Invoice IRN for a generated invoice" />

      <div className="alert alert-warning" style={{ marginBottom: 'var(--space-4)' }}>
        No real GST e-Invoice (NIC/GSP) credentials are configured — IRNs are generated by a mock provider for now, not a genuine government registration. See server/.env.example (GST_IRN_*).
      </div>

      <div style={{ marginBottom: 'var(--space-4)', maxWidth: 360 }}>
        <SearchInput value={search} onChange={setSearch} placeholder="Search invoice no…" />
      </div>

      <DataTable
        columns={[
          { key: 'invoiceNo', header: 'Invoice No', render: (r) => r.invoiceNo },
          { key: 'client', header: 'Client', render: (r) => r.clientId?.name || '-' },
          { key: 'amount', header: 'Amount', align: 'right', render: (r) => formatCurrency(r.amount) },
          { key: 'invoiceDate', header: 'Date', render: (r) => formatDate(r.invoiceDate) },
          {
            key: 'actions', header: '', align: 'right',
            render: (r) => (
              <button type="button" className="btn btn-primary btn-sm" onClick={() => openConfirm(r)}>
                <FileCheck2 size={14} /> Generate IRN
              </button>
            ),
          },
        ]}
        rows={state.rows}
        loading={state.loading}
        error={state.error}
        onRetry={load}
        keyField="_id"
        emptyTitle="No invoices pending an IRN"
        emptyDescription="Every generated invoice already has an IRN, or none exist yet."
      />

      <ConfirmDialog
        open={Boolean(target) && !result}
        title="Generate IRN"
        loading={generating}
        message={
          <div>
            <p>Generate a GST e-Invoice IRN for <strong>{target?.invoiceNo}</strong>?</p>
            {genError && <div className="alert alert-danger" style={{ marginTop: 'var(--space-3)' }}>{genError}</div>}
          </div>
        }
        confirmLabel="Generate IRN"
        onConfirm={confirmGenerate}
        onCancel={() => setTarget(null)}
      />

      {result && target && (
        <div className="alert alert-success" style={{ marginTop: 'var(--space-4)' }}>
          <p className="fw-medium">IRN generated for {target.invoiceNo}</p>
          <div className="grid-2 text-sm" style={{ marginTop: 'var(--space-2)' }}>
            <div><span className="text-muted">Status: </span><StatusBadge status={result.irnStatus} /></div>
            <div><span className="text-muted">Provider: </span>{result.provider}</div>
            <div style={{ gridColumn: '1 / -1' }}><span className="text-muted">IRN: </span><code>{result.irn}</code></div>
            <div><span className="text-muted">Ack No: </span>{result.ackNo}</div>
            <div><span className="text-muted">Ack Date: </span>{formatDate(result.ackDate)}</div>
          </div>
          <button type="button" className="btn btn-secondary btn-sm" style={{ marginTop: 'var(--space-3)' }} onClick={() => { setTarget(null); setResult(null); }}>Close</button>
        </div>
      )}
    </div>
  );
}
