import {
  LayoutDashboard,
  PackagePlus,
  ListOrdered,
  Printer,
  Radar,
  Route as RouteIcon,
  Terminal,
  Users,
  IdCard,
  Truck,
  Wallet,
  Gauge,
  MapPinned,
  Building2,
  Map,
  Landmark,
  Hash,
  ShieldQuestion,
  Barcode,
  BarChart3,
  PieChart,
  TrendingUp,
  ClipboardList,
  ScrollText,
  UserCog,
  UsersRound,
  ShieldCheck,
  KeyRound,
  LockKeyhole,
  Settings,
  Building,
  BookOpenText,
  Sparkles,
  UserCircle,
  Rows3,
  MailPlus,
  FileText,
  FilePlus2,
  FileClock,
  FileSpreadsheet,
  FileDigit,
  ReceiptText,
  BadgeIndianRupee,
  FileSearch2,
  FileCheck2,
  FileBarChart,
  CreditCard,
  History,
  UploadCloud,
  BadgeCheck,
  Calculator,
  NotebookText,
  BookText,
  Scale,
} from 'lucide-react';
import { IMPORT_DEFINITIONS, MASTER_DEFINITIONS } from '../utils/constants';

/**
 * Single source of truth for the sidebar. The Sidebar component renders purely from this
 * array — no hand-written per-section JSX. Order mirrors the discovered reference IA:
 * Dashboard, Operation, Master, Report, Admin Report, User & Permission, Settings,
 * Invoice, Payment, Excel Import, KYC, Accounting.
 */
const navigation = [
  {
    title: 'Dashboard',
    icon: LayoutDashboard,
    path: '/dashboard',
    permission: 'dashboard.read',
  },
  {
    title: 'Operation',
    icon: RouteIcon,
    children: [
      { title: 'New Shipment', icon: PackagePlus, path: '/shipments/create', permission: 'shipments.create' },
      { title: 'Shipment List', icon: ListOrdered, path: '/shipments', permission: 'shipments.read' },
      { title: 'Print AWB', icon: Printer, path: '/shipments/print', permission: 'shipments.read' },
      { title: 'Track Shipment', icon: Radar, path: '/tracking', permission: 'tracking.read' },
      { title: 'Shipment Movement', icon: Truck, path: '/shipment-movement', permission: 'shipments.update' },
      { title: 'API Request/Response', icon: Terminal, path: '/api-request-response', permission: 'shipments.read' },
    ],
  },
  {
    title: 'Master',
    icon: Building2,
    children: [
      { title: 'Client Master', icon: Users, path: '/customers', permission: 'customers.read' },
      { title: 'Client VAS Detail', icon: IdCard, path: '/customers/vas', permission: 'customers.update' },
      { title: 'Vendor Master', icon: Truck, path: '/couriers', permission: 'couriers.read' },
      { title: 'Vendor Account Detail', icon: Wallet, path: '/couriers/accounts', permission: 'couriers.update' },
      { title: 'Vendor Service Configuration', icon: Gauge, path: '/couriers/service-configuration', permission: 'couriers.update' },
      { title: 'Zone Master', icon: Map, path: '/masters/zones', permission: 'masters.read' },
      { title: 'Charge Type Master', icon: BadgeIndianRupee, path: '/masters/charge-types', permission: 'masters.read' },
      { title: 'Client Fuel Charge Master', icon: BadgeIndianRupee, path: '/masters/fuel-charges', permission: 'masters.read' },
      { title: 'Country Master', icon: Landmark, path: '/masters/countries', permission: 'masters.read' },
      { title: 'State Master', icon: Landmark, path: '/masters/states', permission: 'masters.read' },
      { title: 'City Master', icon: Building, path: '/masters/cities', permission: 'masters.read' },
      { title: 'PinCode Master', icon: MapPinned, path: '/masters/pincodes', permission: 'masters.read' },
      { title: 'ODA PinCode Mapping', icon: MapPinned, path: '/masters/oda-pincode-mapping', permission: 'masters.read' },
      { title: 'Tracking Event Mapping', icon: Hash, path: '/masters/tracking-event-mapping', permission: 'masters.read' },
      { title: 'Reason Master', icon: ShieldQuestion, path: '/masters/reasons', permission: 'masters.read' },
      { title: 'HSN Master', icon: Barcode, path: '/masters/hsn', permission: 'masters.read' },
    ],
  },
  {
    title: 'Report',
    icon: BarChart3,
    children: [
      { title: 'Sales Report', icon: PieChart, path: '/reports/sales', permission: 'reports.read' },
      { title: 'Vendor Contribution', icon: BarChart3, path: '/reports/vendor-contribution', permission: 'reports.read' },
      { title: 'Trend Report', icon: TrendingUp, path: '/reports/trend', permission: 'reports.read' },
      { title: 'Client Outstanding', icon: ClipboardList, path: '/reports/client-outstanding', permission: 'reports.read' },
    ],
  },
  {
    title: 'Admin Report',
    icon: ScrollText,
    children: [
      { title: 'User Logs', icon: ScrollText, path: '/reports/user-logs', permission: 'reports.read' },
    ],
  },
  {
    title: 'User & Permission',
    icon: UserCog,
    children: [
      { title: 'Users', icon: Users, path: '/users', permission: 'users.read' },
      { title: 'User Group', icon: UsersRound, path: '/user-groups', permission: 'users.update' },
      { title: 'Group Rights', icon: ShieldCheck, path: '/group-rights', permission: 'users.update' },
      { title: 'User Rights', icon: KeyRound, path: '/user-rights', permission: 'users.update' },
      { title: 'Change Password', icon: LockKeyhole, path: '/change-password' },
    ],
  },
  {
    title: 'Settings',
    icon: Settings,
    children: [
      { title: 'Company Profile', icon: Building, path: '/settings/company-profile', permission: 'settings.update' },
      { title: 'Company Ledger', icon: BookOpenText, path: '/settings/company-ledger', permission: 'settings.read' },
      { title: 'Your Plan', icon: Sparkles, path: '/settings/plan', permission: 'settings.read' },
      { title: 'Your Profile', icon: UserCircle, path: '/settings/profile' },
      { title: 'Grid Page Size', icon: Rows3, path: '/settings/table-page-size', permission: 'settings.update' },
      { title: 'Mail/SMS Format', icon: MailPlus, path: '/settings/mail-sms-format', permission: 'settings.update' },
    ],
  },
  {
    title: 'Invoice',
    icon: FileText,
    children: [
      { title: 'Invoice List', icon: FileText, path: '/invoices', permission: 'invoices.read' },
      { title: 'Generate Client Bill', icon: FilePlus2, path: '/invoices/create', permission: 'invoices.create' },
      { title: 'Re-Generate Client Bill', icon: FileClock, path: '/invoices/regenerate', permission: 'invoices.update' },
      { title: 'Client Rate Entry', icon: FileSpreadsheet, path: '/invoices/client-rate-entry', permission: 'invoices.update' },
      { title: 'Client Tax Rate', icon: FileDigit, path: '/invoices/client-tax-rate', permission: 'invoices.update' },
      { title: 'Vendor Rate Entry', icon: FileSpreadsheet, path: '/invoices/vendor-rate-entry', permission: 'invoices.update' },
      { title: 'Vendor Fuel Surcharge', icon: FileDigit, path: '/invoices/vendor-fuel-surcharge', permission: 'invoices.update' },
      { title: 'Vendor Rate Enquiry', icon: FileSearch2, path: '/invoices/rate-enquiry', permission: 'invoices.read' },
      { title: 'Client Rate Enquiry', icon: FileSearch2, path: '/invoices/client-rate-enquiry', permission: 'invoices.read' },
      { title: 'Generate IRN', icon: ReceiptText, path: '/invoices/irn', permission: 'invoices.update' },
      { title: 'IRN Report', icon: FileCheck2, path: '/invoices/irn/report', permission: 'invoices.read' },
      { title: 'Cash/ToPay Invoice', icon: ReceiptText, path: '/invoices/topay', permission: 'invoices.create' },
      { title: 'Cargo Tax Invoice', icon: ReceiptText, path: '/invoices/cargo-tax', permission: 'invoices.create' },
      { title: 'Billing Report', icon: FileBarChart, path: '/invoices/billing-report', permission: 'invoices.read' },
    ],
  },
  {
    title: 'Payment',
    icon: CreditCard,
    children: [
      { title: 'Payments', icon: CreditCard, path: '/payments', permission: 'payments.read' },
      { title: 'Record Payment', icon: CreditCard, path: '/payments/record', permission: 'payments.create' },
      { title: 'Payment History', icon: History, path: '/payments/history', permission: 'payments.read' },
    ],
  },
  {
    title: 'Excel Import',
    icon: UploadCloud,
    children: IMPORT_DEFINITIONS.map((imp) => ({
      title: imp.title,
      icon: UploadCloud,
      path: `/import/${imp.key}`,
      permission: 'import.create',
    })),
  },
  {
    title: 'KYC',
    icon: BadgeCheck,
    path: '/kyc',
    permission: 'kyc.read',
  },
  {
    title: 'Accounting',
    icon: Calculator,
    children: [
      { title: 'Account Entry', icon: NotebookText, path: '/accounting/entry', permission: 'accounting.update' },
      { title: 'Journal Entry', icon: BookText, path: '/accounting/journal', permission: 'accounting.update' },
      { title: 'Receipt Entry', icon: ReceiptText, path: '/accounting/receipt', permission: 'accounting.update' },
      { title: 'Ledger View', icon: BookOpenText, path: '/accounting/ledger', permission: 'accounting.read' },
      { title: 'Client Outstanding', icon: Scale, path: '/accounting/client-outstanding', permission: 'accounting.read' },
    ],
  },
];

export { MASTER_DEFINITIONS };
export default navigation;
